"""Finite formal argumentation objects and algorithms."""

from argumentation import (
    af_revision,
    aba,
    accrual,
    adf,
    aspic,
    aspic_encoding,
    aspic_incomplete,
    bipolar,
    dung,
    gradual,
    iccma,
    labelling,
    partial_af,
    preference,
    probabilistic,
    ranking,
    sat_encoding,
    semantics,
    subjective_aspic,
    weighted,
)

__all__ = [
    "af_revision",
    "aba",
    "accrual",
    "adf",
    "aspic",
    "aspic_encoding",
    "aspic_incomplete",
    "bipolar",
    "dung",
    "gradual",
    "iccma",
    "labelling",
    "partial_af",
    "preference",
    "probabilistic",
    "ranking",
    "sat_encoding",
    "semantics",
    "subjective_aspic",
    "weighted",
]
