"""Finite formal argumentation objects and algorithms."""

from argumentation import (
    af_revision,
    accrual,
    aspic,
    aspic_encoding,
    bipolar,
    dung,
    gradual,
    iccma,
    labelling,
    partial_af,
    preference,
    probabilistic,
    ranking,
    sat_encoding,
    semantics,
    value_based,
    weighted,
)

__all__ = [
    "af_revision",
    "accrual",
    "aspic",
    "aspic_encoding",
    "bipolar",
    "dung",
    "gradual",
    "iccma",
    "labelling",
    "partial_af",
    "preference",
    "probabilistic",
    "ranking",
    "sat_encoding",
    "semantics",
    "value_based",
    "weighted",
]
