"""Practical reasoning arguments over action-based transition systems."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Mapping


ValueEffect = Literal["+", "-", "="]
SupportedCriticalQuestion = Literal["CQ5", "CQ6", "CQ11"]


@dataclass(frozen=True)
class PracticalArgument:
    """An AS1/AS2-style presumptive argument for an action.

    Atkinson & Bench-Capon 2007 p. 858 state AS1 as current circumstances,
    action, new circumstances, goal, and promoted value. Page 861 restates it
    over AATS states, joint actions, proposition changes, and value promotion.
    """

    agent: str
    current_state: str
    action: str
    resulting_state: str
    goal: str
    promoted_value: str


@dataclass(frozen=True)
class CriticalQuestionObjection:
    """A concrete objection generated by a supported critical question."""

    question: SupportedCriticalQuestion
    alternative_action: str
    resulting_state: str
    goal: str | None = None
    promoted_value: str | None = None


@dataclass(frozen=True)
class ActionBasedAlternatingTransitionSystem:
    """A compact AATS surface sufficient for AS1 and CQ5/CQ6/CQ11.

    Atkinson & Bench-Capon 2007 pp. 860-861 define AATSs with states, agents,
    actions, action preconditions, transitions, propositions, interpretations,
    values, and a transition valuation ``delta``.
    """

    states: frozenset[str]
    initial_state: str
    agents: frozenset[str]
    actions: frozenset[str]
    preconditions: Mapping[str, frozenset[str]]
    transitions: Mapping[tuple[str, str], str]
    propositions: frozenset[str]
    interpretation: Mapping[str, frozenset[str]]
    values: frozenset[str]
    valuation: Mapping[tuple[str, str, str], ValueEffect]

    def __post_init__(self) -> None:
        if not self.states:
            raise ValueError("states must be non-empty")
        if self.initial_state not in self.states:
            raise ValueError("initial_state must be a state")
        if not self.agents:
            raise ValueError("agents must be non-empty")
        if not self.actions:
            raise ValueError("actions must be non-empty")
        if not self.values:
            raise ValueError("values must be non-empty")

        unknown_precondition_actions = sorted(set(self.preconditions) - self.actions)
        if unknown_precondition_actions:
            raise ValueError(
                "preconditions use unknown actions: "
                f"{unknown_precondition_actions!r}"
            )
        for action, states in self.preconditions.items():
            unknown_states = sorted(states - self.states)
            if unknown_states:
                raise ValueError(
                    f"preconditions for {action!r} use unknown states: {unknown_states!r}"
                )

        for (state, action), target in self.transitions.items():
            if state not in self.states or target not in self.states:
                raise ValueError("transitions must only use known states")
            if action not in self.actions:
                raise ValueError("transitions must only use known actions")

        for state, propositions in self.interpretation.items():
            if state not in self.states:
                raise ValueError(f"interpretation uses unknown state: {state!r}")
            unknown = propositions - self.propositions
            if unknown:
                raise ValueError(f"interpretation uses unknown propositions: {sorted(unknown)!r}")

        for (source, target, value), effect in self.valuation.items():
            if source not in self.states or target not in self.states:
                raise ValueError("valuation must only use known states")
            if value not in self.values:
                raise ValueError(f"valuation uses unknown value: {value!r}")
            if effect not in {"+", "-", "="}:
                raise ValueError(f"unknown value effect: {effect!r}")

    def result(self, state: str, action: str) -> str | None:
        """Return ``tau(state, action)`` when the action is executable."""

        if state not in self.preconditions.get(action, frozenset()):
            return None
        return self.transitions.get((state, action))

    def goal_changed(self, source: str, target: str, goal: str) -> bool:
        """Return whether the goal proposition changes truth value."""

        if goal not in self.propositions:
            raise ValueError(f"unknown proposition: {goal!r}")
        source_truth = goal in self.interpretation.get(source, frozenset())
        target_truth = goal in self.interpretation.get(target, frozenset())
        return source_truth != target_truth

    def effect(self, source: str, target: str, value: str) -> ValueEffect:
        """Return ``delta(source, target, value)``; absent entries are neutral."""

        if value not in self.values:
            raise ValueError(f"unknown value: {value!r}")
        return self.valuation.get((source, target, value), "=")


def critical_question_objections(
    system: ActionBasedAlternatingTransitionSystem,
    argument: PracticalArgument,
    question: str,
) -> tuple[CriticalQuestionObjection, ...]:
    """Generate objections for the supported Atkinson critical questions."""

    _validate_argument(system, argument)
    if question == "CQ5":
        return _cq5(system, argument)
    if question == "CQ6":
        return _cq6(system, argument)
    if question == "CQ11":
        return _cq11(system, argument)
    raise NotImplementedError(f"{question} is not implemented")


def _cq5(
    system: ActionBasedAlternatingTransitionSystem,
    argument: PracticalArgument,
) -> tuple[CriticalQuestionObjection, ...]:
    # Atkinson & Bench-Capon 2007 p. 862, CQ5: an alternative joint action
    # reaches the same resulting state q_y.
    objections = [
        CriticalQuestionObjection(
            question="CQ5",
            alternative_action=action,
            resulting_state=argument.resulting_state,
        )
        for action in sorted(system.actions)
        if action != argument.action
        and system.result(argument.current_state, action) == argument.resulting_state
    ]
    return tuple(objections)


def _cq6(
    system: ActionBasedAlternatingTransitionSystem,
    argument: PracticalArgument,
) -> tuple[CriticalQuestionObjection, ...]:
    # Atkinson & Bench-Capon 2007 p. 862, CQ6: an alternative joint action
    # realises the same goal-level proposition change.
    objections: list[CriticalQuestionObjection] = []
    for action in sorted(system.actions):
        if action == argument.action:
            continue
        target = system.result(argument.current_state, action)
        if target is None:
            continue
        if system.goal_changed(argument.current_state, target, argument.goal):
            objections.append(
                CriticalQuestionObjection(
                    question="CQ6",
                    alternative_action=action,
                    resulting_state=target,
                    goal=argument.goal,
                )
            )
    return tuple(objections)


def _cq11(
    system: ActionBasedAlternatingTransitionSystem,
    argument: PracticalArgument,
) -> tuple[CriticalQuestionObjection, ...]:
    # Atkinson & Bench-Capon 2007 p. 862, CQ11: the proposed action promotes
    # one value, while a different available action promotes another value.
    if system.effect(argument.current_state, argument.resulting_state, argument.promoted_value) != "+":
        return tuple()

    objections: list[CriticalQuestionObjection] = []
    for action in sorted(system.actions):
        if action == argument.action:
            continue
        target = system.result(argument.current_state, action)
        if target is None:
            continue
        for value in sorted(system.values - {argument.promoted_value}):
            if system.effect(argument.current_state, target, value) == "+":
                objections.append(
                    CriticalQuestionObjection(
                        question="CQ11",
                        alternative_action=action,
                        resulting_state=target,
                        promoted_value=value,
                    )
                )
    return tuple(objections)


def _validate_argument(
    system: ActionBasedAlternatingTransitionSystem,
    argument: PracticalArgument,
) -> None:
    if argument.agent not in system.agents:
        raise ValueError(f"unknown agent: {argument.agent!r}")
    if argument.current_state not in system.states:
        raise ValueError(f"unknown current state: {argument.current_state!r}")
    if argument.resulting_state not in system.states:
        raise ValueError(f"unknown resulting state: {argument.resulting_state!r}")
    if argument.action not in system.actions:
        raise ValueError(f"unknown action: {argument.action!r}")
    if argument.goal not in system.propositions:
        raise ValueError(f"unknown goal proposition: {argument.goal!r}")
    if argument.promoted_value not in system.values:
        raise ValueError(f"unknown promoted value: {argument.promoted_value!r}")
    actual = system.result(argument.current_state, argument.action)
    if actual != argument.resulting_state:
        raise ValueError(
            "argument resulting_state must match the AATS transition: "
            f"expected {actual!r}, got {argument.resulting_state!r}"
        )
